# docker-compose.prod.yml
version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    dns:
      - 8.8.8.8
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -C -N -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    user: appuser
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DB_ENGINE=mssql
      - DB_NAME=texcore_db
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=1433
      - DB_DRIVER=ODBC Driver 18 for SQL Server
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_ROOT=/home/appuser/app/staticfiles
    volumes:
      - prod_django_static:/home/appuser/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:${TAG}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - prod_django_static:/var/www/django_static:ro
    depends_on:
      - backend

volumes:
  mssql_data:
  prod_django_static:
